[package]
name = "redix"
version = "0.1.0"
description = "Redix Redis desktop client"
authors = ["Redix"]
edition = "2021"

[lib]
name = "redix_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["test"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
thiserror = "2"
keyring = { version = "4.1", default-features = false, features = ["v1"] }
redis = { version = "1.5", features = ["tokio-comp", "tokio-rustls-comp", "tls-rustls-insecure"] }
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
uuid = { version = "1", features = ["v4"] }

tempfile = "3"
ssh2 = { version = "0.9.5", features = ["vendored-openssl"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", default-features = false, features = ["Win32_Storage_FileSystem"] }
