import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import StreamEntries from "./StreamEntries";
import type { StreamEntriesPage } from "./streamEntriesApi";
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock("@tauri-apps/api/core", () => ({ invoke }));
const page = (id: string, next: string | null = null): StreamEntriesPage => ({ entries: [{ id, fields: [{ field: "event", value: id }] }], next_cursor: next, has_more: next !== null });
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(r => { resolve = r; }); return { promise, resolve }; }
describe("Stream 分页与增量编辑", () => {
  // Desktop WebViews may reject native confirm without displaying a dialog.
  beforeEach(() => { vi.resetAllMocks(); vi.stubGlobal("confirm", vi.fn(() => false)); invoke.mockResolvedValue(page("1-0", "1-0")); });
  afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); });
  it("前后翻页保留精确游标并从服务端切换倒序", async () => {
    invoke.mockImplementation(async (_command, { input }) => input.reverse ? page("9007199254740993-18446744073709551615") : input.cursor ? page("2-0") : page("1-0", "1-0"));
    render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.click(screen.getByRole("button", { name: "下一页消息" }));
    await screen.findByLabelText("选择消息 2-0");
    expect(screen.getByRole("button", { name: "下一页消息" })).toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: "上一页消息" }));
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.change(screen.getByLabelText("消息排序"), { target: { value: "desc" } });
    await screen.findByLabelText("选择消息 9007199254740993-18446744073709551615");
    expect(invoke).toHaveBeenLastCalledWith("get_stream_entries", { input: { connection_id: "local", key: "events", start: "-", end: "+", cursor: null, count: 100, reverse: true } });
  });
  it("原生确认不可用时仍可通过应用内确认新增和删除消息，取消不发送写请求", async () => {
    render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.change(screen.getByLabelText("消息字段 JSON"), { target: { value: '[["a","b"],["a",""]]' } });
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    fireEvent.click(within(screen.getByRole("alertdialog", { name: "确认添加消息" })).getByRole("button", { name: "取消" }));
    fireEvent.click(screen.getByLabelText("选择消息 1-0"));
    fireEvent.click(screen.getByRole("button", { name: "删除选中消息" }));
    fireEvent.click(within(screen.getByRole("alertdialog", { name: "确认删除" })).getByRole("button", { name: "取消" }));
    expect(invoke.mock.calls.every(([command]) => command === "get_stream_entries")).toBe(true);
    invoke.mockImplementation(async (command) => command === "add_stream_entry" ? "3-0" : command === "delete_stream_entries" ? 1 : page("1-0", "1-0"));
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    fireEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "确认添加" }));
    await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("已添加消息 3-0"));
    expect(invoke).toHaveBeenCalledWith("add_stream_entry", { input: { connection_id: "local", key: "events", id: "*", fields: [{ field: "a", value: "b" }, { field: "a", value: "" }] } });
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.click(screen.getByLabelText("选择消息 1-0"));
    fireEvent.click(screen.getByRole("button", { name: "删除选中消息" }));
    fireEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "确认删除" }));
    await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("已删除 1 条消息"));
    expect(invoke).toHaveBeenCalledWith("delete_stream_entries", { input: { connection_id: "local", key: "events", ids: ["1-0"] } });
    expect(window.confirm).not.toHaveBeenCalled();
  });
  it("确认期间重复点击只显示一次提示，提交期间不重复写入", async () => {
    const write = deferred<string>();
    invoke.mockImplementation(async (command) => command === "add_stream_entry" ? write.promise : page("1-0"));
    render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    expect(screen.getAllByRole("alertdialog")).toHaveLength(1);
    expect(invoke.mock.calls.filter(([command]) => command === "add_stream_entry")).toHaveLength(0);
    fireEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "确认添加" }));
    await waitFor(() => expect(screen.getByRole("button", { name: "添加消息" })).toBeDisabled());
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    expect(invoke.mock.calls.filter(([command]) => command === "add_stream_entry")).toHaveLength(1);
    await act(async () => { write.resolve("3-0"); });
    expect(await screen.findByRole("status")).toHaveTextContent("已添加消息 3-0");
  });
  it("操作成功提示在 3 秒后自动消失", async () => {
    invoke.mockImplementation(async (command) => command === "add_stream_entry" ? "3-0" : page("1-0"));
    render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    vi.useFakeTimers();
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    await act(async () => {
      fireEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "确认添加" }));
    });
    expect(screen.getByRole("status")).toHaveTextContent("已添加消息 3-0");
    act(() => { vi.advanceTimersByTime(3000); });
    expect(screen.queryByRole("status")).not.toBeInTheDocument();
  });
  it.each(["add", "delete"])("切换键会取消尚未提交的 %s 确认，返回后旧按钮也不能写入", async (kind) => {
    const { rerender } = render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    if (kind === "delete") fireEvent.click(screen.getByLabelText("选择消息 1-0"));
    fireEvent.click(screen.getByRole("button", { name: kind === "add" ? "添加消息" : "删除选中消息" }));
    const oldAccept = within(screen.getByRole("alertdialog")).getByRole("button", { name: kind === "add" ? "确认添加" : "确认删除" });
    rerender(<StreamEntries connectionId="local" streamKey="other" />);
    await screen.findByLabelText("选择消息 1-0");
    expect(screen.queryByRole("alertdialog")).not.toBeInTheDocument();
    rerender(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.click(oldAccept);
    expect(invoke.mock.calls.every(([command]) => command === "get_stream_entries")).toBe(true);
  });
  it("父级变为忙碌时取消待定确认，恢复后可以重新确认", async () => {
    const { rerender } = render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    expect(screen.getByRole("alertdialog")).toBeInTheDocument();
    rerender(<StreamEntries connectionId="local" streamKey="events" disabled />);
    expect(screen.queryByRole("alertdialog")).not.toBeInTheDocument();
    expect(invoke.mock.calls.every(([command]) => command === "get_stream_entries")).toBe(true);
    rerender(<StreamEntries connectionId="local" streamKey="events" />);
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    expect(screen.getByRole("alertdialog")).toBeInTheDocument();
  });
  it("离开再返回同一键时旧分页与写入响应都不能覆盖当前页面", async () => {
    const oldPage = deferred<StreamEntriesPage>();
    const oldWrite = deferred<string>();
    invoke.mockImplementation(async (command, { input }) => command === "add_stream_entry" ? oldWrite.promise : input.cursor ? oldPage.promise : page("1-0", "1-0"));
    const changed = vi.fn();
    const { rerender } = render(<StreamEntries connectionId="local" streamKey="events" onChanged={changed} />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.click(screen.getByRole("button", { name: "下一页消息" }));
    rerender(<StreamEntries connectionId="other" streamKey="events" onChanged={changed} />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.change(screen.getByLabelText("消息字段 JSON"), { target: { value: '[["a","b"]]' } });
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    fireEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "确认添加" }));
    await waitFor(() => expect(invoke).toHaveBeenCalledWith("add_stream_entry", { input: { connection_id: "other", key: "events", id: "*", fields: [{ field: "a", value: "b" }] } }));
    rerender(<StreamEntries connectionId="local" streamKey="other" onChanged={changed} />);
    await screen.findByLabelText("选择消息 1-0");
    rerender(<StreamEntries connectionId="other" streamKey="events" onChanged={changed} />);
    await screen.findByLabelText("选择消息 1-0");
    const requestCount = invoke.mock.calls.length;
    await act(async () => { oldPage.resolve(page("old-0")); oldWrite.resolve("99-0"); await oldWrite.promise; });
    expect(screen.queryByLabelText("选择消息 old-0")).not.toBeInTheDocument();
    expect(screen.queryByText(/99-0/)).not.toBeInTheDocument();
    expect(changed).not.toHaveBeenCalled();
    expect(invoke).toHaveBeenCalledTimes(requestCount);
  });
  it("拒绝浮点精度丢失的范围和空字段，服务端失败保留用户输入且隐藏底层错误", async () => {
    render(<StreamEntries connectionId="local" streamKey="events" />);
    await screen.findByLabelText("选择消息 1-0");
    fireEvent.change(screen.getByLabelText("消息范围起点"), { target: { value: "9007199254740993-0" } });
    fireEvent.change(screen.getByLabelText("消息范围终点"), { target: { value: "9007199254740992-0" } });
    fireEvent.click(screen.getByRole("button", { name: "应用消息范围" }));
    expect(screen.getByRole("alert")).toHaveTextContent("范围");
    fireEvent.change(screen.getByLabelText("消息字段 JSON"), { target: { value: "[]" } });
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    expect(screen.getByRole("alert")).toHaveTextContent("字段");
    invoke.mockRejectedValue({ code: "COMMAND_FAILED", message: "secret" });
    fireEvent.change(screen.getByLabelText("消息字段 JSON"), { target: { value: '[["a","b"]]' } });
    fireEvent.click(screen.getByRole("button", { name: "添加消息" }));
    fireEvent.click(within(screen.getByRole("alertdialog")).getByRole("button", { name: "确认添加" }));
    await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("Stream 消息操作失败"));
    expect(screen.getByRole("alert")).not.toHaveTextContent("secret");
    expect(screen.getByLabelText("消息字段 JSON")).toHaveValue('[["a","b"]]');
  });
});
